feat: controller init
Lipoic/Lipoic-Backend pull request #16
Opened 2022-10-25 13:43 UTC by SnowFireWolf

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-25 13:52 UTC, SiongSng requested changes
Looks good.
just a little problem.

2022-10-25 13:52 UTC, SiongSng commented on src/router/api/authentication/controller.ts
> +export const googleAuth = async (req: Request, res: Response) => {
應該是 `googleOAuth` 才對，其他 function 亦同

2022-10-25 14:09 UTC, SiongSng requested changes

2022-10-25 14:09 UTC, SiongSng commented on src/router/api/user/controller.ts
> +export const updateInfo = async (req: Request, res: Response) => {
```suggestion
export const editInfo = async (req: Request, res: Response) => {
```
應該是 `editInfo`

2022-10-25 15:19 UTC, SiongSng requested changes

2022-10-25 15:19 UTC, SiongSng commented on src/router/api/user/data.d.ts
> + * The data for editing user info.
```suggestion
 * The data for updating user info.
```

2022-10-25 15:19 UTC, SiongSng commented on src/router/api/user/controller.ts
> +    #swagger.description = 'Edit the info of the current user (authorization required)'
```suggestion
    #swagger.description = 'Update the info of the current user (authorization required)'
```

2022-10-26 06:56 UTC, Luminous-Coder commented
Sorry, but did you read the guideline?

2022-10-26 09:00 UTC, SiongSng approved these changes
LGTM

2022-10-26 09:09 UTC, merged