feat: create classroom
Lipoic/Lipoic-Backend pull request #20
Opened 2022-12-21 13:37 UTC by SiongSng

# Description
Add create a classroom API

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-12-30 03:40 UTC, Luminous-Coder commented on src/model/auth/connect_account.ts
> +   * The type of the connect account.
建議改成 type of connection

2023-01-01 11:26 UTC, Luminous-Coder commented on src/model/auth/connect_account.ts
> +   * Type of the connect account.
喔，我的意思是，connect 是動詞

2023-01-02 03:35 UTC, Luminous-Coder requested changes
`src/router/api/classroom/controller.ts` 有註解少句號。

2023-01-02 03:35 UTC, Luminous-Coder commented
`src/util/util.ts` 檔名是不是可以再好一點？

2023-01-02 04:52 UTC, SiongSng commented
> `src/util/util.ts` 檔名是不是可以再好一點？

但這部份的內容都比較雜，我想不太到更好的名稱

2023-01-02 04:55 UTC, SiongSng commented
> `src/router/api/classroom/controller.ts` 有註解少句號。

改好了

2023-01-02 06:08 UTC, a3510377 approved these changes

2023-01-02 06:18 UTC, Luminous-Coder approved these changes

2023-01-02 06:49 UTC, SiongSng commented
ready for merge?

2023-01-02 09:13 UTC, merged