feat: join a class
Lipoic/Lipoic-Backend pull request #25
Opened 2023-01-13 14:43 UTC by SiongSng

# Description
Join a class

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-01-14 10:42 UTC, Luminous-Coder requested changes
The style is not consistent.

2023-01-14 10:42 UTC, Luminous-Coder commented on src/router/api/class/index.ts
> +  */
src/router/api/class/index.ts:26

2023-01-14 10:42 UTC, Luminous-Coder commented on src/router/api/class/controller.ts
> +  */
src/router/api/class/controller.ts:199

2023-01-14 10:42 UTC, Luminous-Coder commented on src/router/api/class/controller.ts
> +      */
src/router/api/class/controller.ts:167

2023-01-14 10:42 UTC, Luminous-Coder commented on src/router/api/class/controller.ts
> +    */
src/router/api/class/controller.ts:135

2023-01-16 08:34 UTC, Luminous-Coder requested changes
I found one more.

2023-01-16 08:34 UTC, Luminous-Coder commented on src/router/api/class/index.ts
> +   #swagger.description = 'Create a new class. (authorization required)'
the indent

2023-01-16 08:36 UTC, Luminous-Coder commented
希望下次你可以在push之前看仔細一點
https://github.com/Lipoic/Lipoic-Backend/pull/25/commits/cd3e511004c2b88d721ec52343e13540a3fb8fd1

2023-01-16 09:15 UTC, Luminous-Coder commented on src/router/api/class/index.ts
> +   #swagger.description = 'Create a new class. (authorization required)'
i mean the comment block

2023-01-16 12:56 UTC, SiongSng commented on src/router/api/class/index.ts
> +   #swagger.description = 'Create a new class. (authorization required)'
改好了

2023-01-19 15:24 UTC, Luminous-Coder reviewed
Note:
Actually, for a user, a private class which the user wasn't invited to is not found (or not visible).
It's just like the fact that Hogwarts is invisible for a muggle.

2023-01-19 15:24 UTC, Luminous-Coder commented on src/router/api/class/controller.ts
> +      // Here is a deliberate to return the status that the class does not exist, to avoid causing some security problems.
```suggestion
      // It's deliberately designed to return not-found status to avoid potential secuerity issues.
```
This line is too long.

2023-01-19 15:36 UTC, SiongSng commented on src/router/api/class/controller.ts
> +      // Here is a deliberate to return the status that the class does not exist, to avoid causing some security problems.
thanks

2023-02-26 12:47 UTC, Luminous-Coder submitted a review, later dismissed

2023-03-05 04:03 UTC, Luminous-Coder commented on src/router/api/class/controller.ts
> +    !isPrivate || (isPrivate && aClass?.allowJoinMembers?.includes(user.id));
Is `isPrivate &&` needed?

2023-03-05 04:47 UTC, SiongSng commented on src/router/api/class/controller.ts
> +    !isPrivate || (isPrivate && aClass?.allowJoinMembers?.includes(user.id));
對欸！感謝建議
其實不需要這個檢查，我等等修改，現在在外面

2023-03-07 13:49 UTC, Luminous-Coder requested changes
Tests aren't enough

2023-03-08 04:43 UTC, Luminous-Coder requested changes
Need tests for joining a class without the permission.

2023-03-08 04:43 UTC, Luminous-Coder commented on test/router/api/class/class_api.test.ts
> +  it('Anyone be able to join a public class', async () => {
```suggestion
  it('Anyone is able to join a public class', async () => {
```

2023-03-08 15:15 UTC, SiongSng commented
> Need tests for joining a class without the permission.

@Luminous-Coder 你的沒有權限是指？`role` 還是 `visibility`

2023-03-08 15:46 UTC, Luminous-Coder commented
> 

後者，我看好像沒測到嘗試加入未受邀請的班級，其實也沒測到加入被邀請的的情況。

2023-03-11 09:34 UTC, Luminous-Coder requested changes

2023-03-11 09:34 UTC, Luminous-Coder commented on src/model/class/class_visibility.ts
> +   * A public class can be joined by anyone or search by anyone.
```suggestion
   * A public class can be joined by anyone or searched by anyone.
```
maybe?

2023-03-11 09:34 UTC, Luminous-Coder commented on src/model/class/class_visibility.ts
> +   * A private class can be joined by anyone with the class id.
```suggestion
   * A private class can be joined by anyone with the class ID.
```

2023-03-11 09:34 UTC, Luminous-Coder commented on src/router/api/class/controller.ts
> +          'The class does not exist or its owner does not allow the user to join it.',
```suggestion
          'The class doesn\'t exist or the user wasn\'t invited.',
```

2023-03-11 10:29 UTC, Luminous-Coder commented
COMMIT MESSAGE PLZ
Who knows what "Update filename" is?

2023-03-11 10:31 UTC, SiongSng commented
> COMMIT MESSAGE PLZ
> Who knows what "Update filename" is?

那個是 GitHub 自動生成的，我改不了

2023-03-11 11:05 UTC, Luminous-Coder commented
> > COMMIT MESSAGE PLZ
> > Who knows what "Update filename" is?
> 
> 那個是 GitHub 自動生成的，我改不了

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request
🤔

2023-03-11 11:13 UTC, SiongSng commented
> > > COMMIT MESSAGE PLZ
> > > Who knows what "Update filename" is?
> > 
> > 
> > 那個是 GitHub 自動生成的，我改不了
> 
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request thinking

我是使用手機版 無法修改

2023-03-11 13:26 UTC, Luminous-Coder approved these changes

2023-03-11 14:13 UTC, SiongSng commented
ready for merge?

2023-03-11 14:26 UTC, merged