refactor: router-framework
Lipoic/Lipoic-Backend pull request #9
Opened 2022-09-21 12:51 UTC by banahaker

# Description

Fixed redundant class used, make code clear
# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas

2022-09-21 12:59 UTC, banahaker commented
i fixed some problem

2022-09-22 10:54 UTC, Luminous-Coder requested changes

2022-09-22 10:54 UTC, Luminous-Coder commented on src/router/util/code.ts
>  enum CodeMessage {
Use consistent name instead.

2022-09-22 10:56 UTC, Luminous-Coder commented
BTW, I don't recommend commit messages like those.

2022-09-23 15:16 UTC, Luminous-Coder requested changes

2022-09-23 15:16 UTC, lumynou5 commented on src/router/util/code.ts
> +enum ResponseStatusCodeMessage {
This enumeration is no need.

2022-09-23 15:32 UTC, SiongSng requested changes

2022-09-23 15:32 UTC, SiongSng commented on test/router/router.test.ts
> +    data: 'Router not found.',
這不用 data

2022-09-23 15:32 UTC, SiongSng commented on src/router/index.ts
> +    'Router not found.'
這沒有 data

2022-09-23 15:33 UTC, SiongSng commented on src/router/util/code.ts
> +enum ResponseStatusCodeMessage {
前提在有 docs 的情況下 建議至少先留下註解在 code 那

2022-09-23 15:50 UTC, Luminous-Coder submitted a review, later dismissed

2022-09-24 06:24 UTC, SiongSng requested changes

2022-09-24 06:24 UTC, SiongSng commented on src/router/index.ts
> +  const responsePack: APIResponseData<string> = createResponse(
為什麼要先將回應設定成一個變數再 send
可以直接套進去吧 XD

2022-09-24 06:24 UTC, SiongSng commented on src/router/util/response.ts
> +export interface APIResponseData<T> {
應該叫做 `APIResponse` 即可

2022-09-24 06:24 UTC, SiongSng commented on src/router/util/response.ts
> +  http_status_code: HttpStatusCode;
這是回傳給 client 的內容，不必在資料結構留下 Http Status Code，直接在下方的 `sendResponse` function 提供 Http Status Code 即可

2022-09-24 06:24 UTC, SiongSng commented on src/router/util/response.ts
> +  responseData: APIResponseData<T>
> 這是回傳給 client 的內容，不必在資料結構留下 Http Status Code，直接在下方的 sendResponse function 提供 Http Status Code 即可

我是指這裡，就參數加上一個 `http_status_code`

2022-09-24 06:24 UTC, SiongSng commented on src/router/util/response.ts
> +  http_status_code = HttpStatusCode.OK,
> 這是回傳給 client 的內容，不必在資料結構留下 Http Status Code，直接在下方的 sendResponse function 提供 Http Status Code 即可

所以這裡的 `http_status_code` 也可以刪除

2022-09-24 07:16 UTC, SiongSng approved these changes
LGTM

2022-09-24 07:20 UTC, merged